channels:
  - conda-forge
dependencies:
  - python >=3.12
  - numpy >=2.0.0
  - hpc >=0.1.4
  - pip >=24.0.0
  - matplotlib >=3.8.4
  - ffmpeg-python
  - pytest >=8.2.2
  - pytest-cov >=5.0.0
  - setuptools >=70.1.1
