channels:
  - conda-forge
dependencies:
  - pip >=21.3.1
  - matplotlib >=3.8.4
  - numpy >=2.0.0
  - numpydoc==1.1.0
  - typing-extensions==3.10.*
  - pip:
    - pydata_sphinx_theme>=0.15.2
    - sphinxcontrib-napoleon
    - nbsphinx
    - graphviz
    - ../.
